#!/usr/bin/env node
/**
 * Embed @xterm/xterm + @xterm/addon-fit into src/generated/xtermAssets.ts
 * so spectator/viewer pages stay CSP-safe (inline only, no CDN).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const css = readFileSync(join(root, 'node_modules/@xterm/xterm/css/xterm.css'), 'utf8');
const js = readFileSync(join(root, 'node_modules/@xterm/xterm/lib/xterm.js'), 'utf8')
  .replace(/\/\/# sourceMappingURL=.*$/m, '')
  .replace(/<\/script/gi, '<\\/script');
const fit = readFileSync(join(root, 'node_modules/@xterm/addon-fit/lib/addon-fit.js'), 'utf8')
  .replace(/\/\/# sourceMappingURL=.*$/m, '')
  .replace(/<\/script/gi, '<\\/script');
const hash = createHash('sha256').update(css + js + fit).digest('hex').slice(0, 12);
mkdirSync(join(root, 'src/generated'), { recursive: true });
writeFileSync(
  join(root, 'src/generated/xtermAssets.ts'),
  `/**
 * AUTO-GENERATED by scripts/embed-xterm.mjs — do not edit by hand.
 * xterm.js + Fit addon inlined for CSP-safe spectator/viewer pages
 * (script-src 'unsafe-inline'; no CDN).
 * bundle-hash: ${hash}
 */
export const XTERM_CSS: string = ${JSON.stringify(css)};
export const XTERM_JS: string = ${JSON.stringify(js)};
export const XTERM_FIT_JS: string = ${JSON.stringify(fit)};
`,
);
console.log('wrote src/generated/xtermAssets.ts', hash);
